### ISSUE TITLE
Bookmark/Book synchronisation without root

### ISSUE THREAD

**Issue by Hooloovoo** [geometer/FBReaderJ#105]
For me, synchronising my books/bookmarks between devices is crucial for ebook readers. 

I understand that FBSync:
http://www.mobileread.com/forums/archive/index.php/t-119184.html
https://play.google.com/store/apps/details?id=com.asd.fbsync&hl=en
achieves this, but requires root access on Android devices so that it can access FBReader internals. It would be great if this (or equivalent) functionality could be added into FBReader, so that root access was not necessary to sync bookmarks and books.

I suspect that, if FBSync comes up with a decent solution, other ebook readers would also adopt it.

**Comment by geometer** [comment]
It is implemented via https://books.fbreader.org/

**Comment by jnizniowski** [comment]
There's no bookmarks sync... yet. It's crucial feature for me.
