### ISSUE TITLE
Comic book (CBZ, CBR) support

### ISSUE THREAD

**Issue by mcandre** [geometer/FBReaderJ#132]
Could we add support for reading comic books? CBZ and CBR files are formatted similar to ePUB (zipped images), but have a much simpler, flatter structure.

**Comment by goodevilgenius** [comment]
Just found this old issue. It's been resolved: https://fbreader.org/content/fbreader-comicbook-plugin

**Comment by geometer** [comment]
Yes, it is resolved.
