### ISSUE TITLE
Redundant percentage sign in settings

### ISSUE THREAD

**Issue by dennis-sheil** [geometer/FBReaderJ#140]
This seems to be a problem in German, Belarusian, Thai, Vietnamese and Taiwanese when I test it on an ICS device.

In German language mode -
Click the menu button
Click Einstellungen
Click Aussehen

Under Ausschalten des Bildschirms verhindern it correctly shows
Falls Akkuladung > 25% or
Falls Akkuladung > 50%

But when you click on Ausschalten des Bildschirms verhindern it shows
Falls Akkuladung > 25%% or
Falls Akkuladung > 50%%

There is an extra percentage sign at the end.

This happens not only in German, but in some of the other languages as well.

**Comment by liquiddandruff** [comment]
I've tried to fix this for a while, and had difficulties trying to find where exactly the node values are formatted. I have tried escaping with \%%, just one % (which causes crash as expected), using unicode, using custom entityMap substitution. We would probably be able to fix this problem at the line that tries to format the values.

**Comment by liquiddandruff** [comment]
Pardon the mess lol, use the last one.
