### ISSUE TITLE
Proprietary dependencies

### ISSUE THREAD

**Issue by sbaconnais** [geometer/FBReaderJ#223]
FBReader for Android is supposed to be an open source software but there is a lot of proprietary dependencies in it.

It's problematic since we can't compile source code for android 4.1+ devices which are not using Google Play, and we can't use it in full open source environment since it's using proprietary dictionary api.

Please clarify the situation of FBReader open source policy.

Note : using specific programs such as Yota SDK is a bit problematic too ...

Thanks.

**Comment by geometer** [comment]
I think this can be marked as resolved.
