### ISSUE TITLE
Feature request: Commentable bookmark, underline

### ISSUE THREAD

**Issue by tamo** [geometer/FBReaderJ#226]
The functionality I want the most is "Note to book."
You make notes on pages of real books, don't you?

An example UI is:
`Long-tap somewhere -> (select word(s)) -> Icons are shown -> Tap Bookmark icon -> Choose a style -> Input text`
and afterward,
`Tap a bookmarked position -> The note you made (and style-selecters and a delete-button) are shown`
Also, bookmark-list will list the notes (if available) instead of (or in addition to) selected positions.

With this ability, you may want one more: "Underlined style."
Currently you can only highlight bookmarks.
Isn't it nice if you can underline them?
(It would be useful on e-ink devices or for color-blind people, too)

Of course you may want to seperate bookmarking and noting.
If so, the UI will be something like this:
`Long-tap somewhere -> (select word(s)) -> Icons _and_ an input-field are shown -> Input text`
With this UI, bookmark-list will not be polluted by notes even if you make a lot of notes.
Hmm, now I prefer this one to the commentable bookmarks.

By the way, some e-book readers have a preference option
to easily underline, i.e. `Long-tap -> Select words -> Done` (underlined without any icons or messages).
I don't use it, but it would be useful for some people who underline a lot.

**Comment by frodberserk** [comment]
For this, I modified the Bookmarks table in SQLiteBooksDatabase.java. I added an extra column of notes in the Bookmarks table. This is my SQLiteBooksDatabase.java class: http://pastie.org/pastes

You have to add the notes variable in Bookmarks class to and also add its getter and setter.

**Comment by tamo** [comment]
I'd like to close this issue because it is mostly implemented.
If you want more, you'd open another issue.
