### ISSUE TITLE
[Feature Request] Collections/Sets

### ISSUE THREAD

**Issue by Corelogik** [geometer/FBReaderJ#256]
It would be nice to be able to create and assign books to "collections" or "sets" so that similarly themed, or sequential books could be more easily kept together for easy access. I'm thinking similarly to how they are handled in Aldiko and similar readers.

For example, Tom Clancy's Jack Ryan series books could be kept together in a set, rather than having to scroll through all Tom Clancy books in a directory to find the specific title desired.

**Comment by liquiddandruff** [comment]
If I'm not mistaken, this can be addressed by assuring your ebooks have the proper metadata set (particularly the series field), which would allow you to view and sort your library by "collections", ie, series.

**Comment by geometer** [comment]
This is implemented in Bookshelf plugin, 1.2 beta. User can create and manage "custom shelves". In plans: save order of books on these custom shelves, synchronise via cloud.
