### ISSUE TITLE
Library view freezes when PDF plugin 1.0.3 installed

### ISSUE THREAD

**Issue by krid** [geometer/FBReaderJ#286]
With the plugin installed I can open my library (Open Library => File tree => FBReader library), but once the library screen opens the app freezes.  After about 10s the OS says it's not responding.  Uninstalling the plugin fixes the problem.  Happens on a Nexus 5 and a Nexus 7 2013, both running the latest Lollipop.  I've got mostly epubs, and a few PDFs in the library.

**Comment by geometer** [comment]
Hi,

If you really have few pdfs, is it possible to share these pdfs with me? Looks like the problem is in processing of some PDF file.

**Comment by krid** [comment]
I did some experimentation.  It looks like the problem happens for any PDF, but it only happens when I scroll the PDF into the viewport.  I had a PDF whose filename started with A, so the list view would freeze up as soon as I opened it.  Then I took out most of the PDFs, leaving only one whose name started with W.  Now I can scroll the list view up and down repeatedly, until I try to bring the PDF into the viewport, at which point the list view freezes.  Similarly, I can navigate down into other folders and scroll them around, up until I try to scroll a PDF into view, when it freezes.

It's not a particular PDF, it's any PDF, but for the sake of argument, here's one that causes a freeze:
 http://otisbean.com/dropbox/wallace_stevens_2004_9.pdf

**Comment by geometer** [comment]
Hi Dirk,

Could you please try updated plugin from http://fbreader.org/content/fbreader-pdf-plugin? It work fine with your file on my device.

**Comment by krid** [comment]
That seems to fix the problem, thanks for the quick work.

**Comment by geometer** [comment]
Oh, great! Will release this version as a bugfix.
