### ISSUE TITLE
TOC marks not shown on statusbar when there are more than 100 TOC entries

### ISSUE THREAD

**Issue by gvb1234** [geometer/FBReaderJ#290]
When a book contains more than 100 TOC entries, no TOC mark is shown on the status bar. The culprit is the line

                private final int MAX_TOC_MARKS_NUMBER = 100;

in FBView.java. Increasing the max value to some bigger number fixes the problem.

**Comment by geometer** [comment]
Since 2.5.10 there will be an option for maximum number of marks

**Comment by gvb1234** [comment]
Thank you!!
