### ISSUE TITLE
Text Selection bug

### ISSUE THREAD

**Issue by frodberserk** [geometer/FBReaderJ#293]
There is a text selection bug. While selecting text, if we drag the cursor to the bottom of the page, it keeps scrolling the page (i.e content of next page are visible). Same behaviour for top of the page. Please have a look at it! Thanks.

**Comment by liquiddandruff** [comment]
This is intended behavior: if a user wants to select a passage of text that spans more than one page, how else would it be done? Maybe I do not understand your question.

**Comment by frodberserk** [comment]
But it violates the concept of pagination, isn't it?

**Comment by frodberserk** [comment]
For real book reading effect, the page must not scroll IMO.

**Comment by intari** [comment]
this behavior is why I like FBreader. How else user supposed to perform selection across pages?

**Comment by frodberserk** [comment]
@intari By highlighting the parts differently.

**Comment by frodberserk** [comment]
Is there any workaround for not scrolling the page? I understood that scrolling is a feature while selection, but I want to make a real book experience which will fix the page.

**Comment by frodberserk** [comment]
Done. I just commented the scroller inside ZLTextSelection class. Just modified the function:

    void expandTo(ZLTextPage page, int x, int y) {
        if (isEmpty()) {
            return;
        }

        final ZLTextElementAreaVector vector = page.TextElementMap;
        final ZLTextElementArea firstArea = vector.getFirstArea();
        final ZLTextElementArea lastArea = vector.getLastArea();
//        if (firstArea != null && y < firstArea.YStart) {
//            if (myScroller != null && myScroller.scrollsForward()) {
//                myScroller.stop();
//                myScroller = null;
//            }
//            if (myScroller == null) {
//                myScroller = new Scroller(page, false, x, y);
//                return;
//            }
//        } else if (lastArea != null && y + ZLTextSelectionCursor.getHeight() / 2 + ZLTextSelectionCursor.getAccent() / 2 > lastArea.YEnd) {
//            if (myScroller != null && !myScroller.scrollsForward()) {
//                myScroller.stop();
//                myScroller = null;
//            }
//            if (myScroller == null) {
//                myScroller = new Scroller(page, true, x, y);
//                return;
//            }
//        } else {
        if (myScroller != null) {
            myScroller.stop();
            myScroller = null;
        }
//        }

        if (myScroller != null) {
            myScroller.setXY(x, y);
        }

        ZLTextRegion region = myView.findRegion(x, y, ZLTextView.MAX_SELECTION_DISTANCE, ZLTextRegion.AnyRegionFilter);
        if (region == null && myScroller != null) {
            region = myView.findRegion(x, y, ZLTextRegion.AnyRegionFilter);
        }
        if (region == null) {
            return;
        }

        final ZLTextRegion.Soul soul = region.getSoul();
        if (myCursorInMovement == ZLTextSelectionCursor.Right) {
            if (myLeftMostRegionSoul.compareTo(soul) <= 0) {
                myRightMostRegionSoul = soul;
            } else {
                myRightMostRegionSoul = myLeftMostRegionSoul;
                myLeftMostRegionSoul = soul;
                myCursorInMovement = ZLTextSelectionCursor.Left;
            }
        } else {
            if (myRightMostRegionSoul.compareTo(soul) >= 0) {
                myLeftMostRegionSoul = soul;
            } else {
                myLeftMostRegionSoul = myRightMostRegionSoul;
                myRightMostRegionSoul = soul;
                myCursorInMovement = ZLTextSelectionCursor.Right;
            }
        }

        if (myCursorInMovement == ZLTextSelectionCursor.Right) {
            if (hasPartAfterPage(page)) {
                myView.turnPage(true, ZLTextView.ScrollingMode.SCROLL_LINES, 1);
                myView.Application.getViewWidget().reset();
                myView.preparePaintInfo();
            }
        } else {
            if (hasPartBeforePage(page)) {
                myView.turnPage(false, ZLTextView.ScrollingMode.SCROLL_LINES, 1);
                myView.Application.getViewWidget().reset();
                myView.preparePaintInfo();
            }
        }
    }
