### ISSUE TITLE
Error Renaming Package

### ISSUE THREAD

**Issue by bhuwneshjoshi** [geometer/FBReaderJ#318]
While renaming the package in android eclipse, I am getting an error W/System.err(10980): java.lang.NoClassDefFoundError: org/geometerplus/fbreader/formats/PluginCollection and such errors, I renamed the package in manifest.xml by using refactor->rename. Can anybody tell me what is the issue.

**Comment by geometer** [comment]
Sure, I can. You trying to steal code with no understanding programming at all. That's standard issue.
