### ISSUE TITLE
Unable to change package name of FbReader code in Android Code.

### ISSUE THREAD

**Issue by AmanChugh** [geometer/FBReaderJ#332]
I am developing android app using FbReader openSource code. 
I compiled and run default code It run successfully. But When I try to change the package name of code then it throw an error. 
and when I manually edit the package name and compile code then FbReader is unable to load library and any book.

**Comment by AmanChugh** [comment]
Can yo please check this issue.

**Comment by geometer** [comment]
do you develop open-source application?

**Comment by AmanChugh** [comment]
yes.

**Comment by e-erbolat** [comment]
I also have this problem, you were able to solve it?

**Comment by e-erbolat** [comment]
I solve this problem. Change value for DEFAULT_PACKAGE in FBReaderIntents class

**Comment by geometer** [comment]
Sorry guys, this is not stackoverflow
