### ISSUE TITLE
Not all books on SD card show up

### ISSUE THREAD

**Issue by jgissend10** [geometer/FBReaderJ#333]
I have a NSTG and not all books on my SD card are showing up. I have about 500 books and only a small portion of those seem to be getting indexed. I can see them under File Tree and it can read them, but they don't show up under By Author or the other parts of Library.

**Comment by liquiddandruff** [comment]
I get this problem frequently too. I feel that FBReader's indexing and searching hasn't worked reliably for some time now.

**Comment by geometer** [comment]
looks like it crashes on some files and stops scanning. we need to have these files for testing

**Comment by jgissend10** [comment]
Is there a way for me to tell which files it is crashing on?

**Comment by geometer** [comment]
Can you please send me the log? I can add additional debug printings if the log will be not informative enough.

**Comment by jgissend10** [comment]
The issue seems to have resolved itself on my device. Not sure what changed in my books.
