### ISSUE TITLE
Cannot login to books.fbreader.org

### ISSUE THREAD

**Issue by Pastafarianist** [geometer/FBReaderJ#334]
I am trying to login to a previously created account. I have two-factor authentication enabled in my Google Account, and the Google Authenticator is installed on the same device where I'm trying to login in FBReader. After switching from FBReader to Authenticator and then back, I type my one-time password and tap "login". Then a bunch of redirects happen and I eventually end up on `https://books.fbreader.org/static/empty.html#`. After that, nothing else happens. If I tap the "back" button, there is a toast saying "Authentication failed".

**Comment by geometer** [comment]
Just update fbreader to the latest version.

**Comment by Pastafarianist** [comment]
Damn, it was an F-Droid build.
Well, okay, guess I can't get the best of two worlds. Thanks!

**Comment by geometer** [comment]
Yes, that's known issue -- we just forget about this #. :(

**Comment by geometer** [comment]
This commit, if you can push it to f-droid sources...

https://github.com/geometer/FBReaderJ/commit/847bb76dbd9815397836c4226c567fd8a03c5927

**Comment by Pastafarianist** [comment]
I'm not related to F-Droid developers, just using their repository, unfortunately.
