### ISSUE TITLE
:fBReaderJmaster:compileDebugNdk Build failed 

### ISSUE THREAD

**Issue by NemoNguyen** [geometer/FBReaderJ#335]
Dear,
Please help me, i build this project but got this error. Please help me how to fix it.
Thank you all 

:fBReaderJmaster:compileDebugNdk
AGPBI: {"kind":"SIMPLE","text":"C:\\Users\\QuocN\\StudioProjects\\FBReaderJ-master\\fBReaderJmaster\\src\\main\\jni\\DeflatingDecompressor\\DeflatingDecompressor.cpp:83:1: fatal error: opening dependency file C:\\Users\\QuocN\\StudioProjects\\FBReaderJ-master\\fBReaderJmaster\\build\\intermediates\\ndk\\debug\\obj/local/arm64-v8a/objs/DeflatingDecompressor-v3/C_\\Users\\QuocN\\StudioProjects\\FBReaderJ-master\\fBReaderJmaster\\src\\main\\jni\\DeflatingDecompressor\\DeflatingDecompressor.o.d: No such file or directory","position":{},"original":"C:\\Users\\QuocN\\StudioProjects\\FBReaderJ-master\\fBReaderJmaster\\src\\main\\jni\\DeflatingDecompressor\\DeflatingDecompressor.cpp:83:1: fatal error: opening dependency file C:\\Users\\QuocN\\StudioProjects\\FBReaderJ-master\\fBReaderJmaster\\build\\intermediates\\ndk\\debug\\obj/local/arm64-v8a/objs/DeflatingDecompressor-v3/C_\\Users\\QuocN\\StudioProjects\\FBReaderJ-master\\fBReaderJmaster\\src\\main\\jni\\DeflatingDecompressor\\DeflatingDecompressor.o.d: No such file or directory"}
AGPBI: {"kind":"SIMPLE","text":" }","position":{},"original":" }"}
AGPBI: {"kind":"SIMPLE","text":" ^","position":{},"original":" ^"}
AGPBI: {"kind":"SIMPLE","text":"compilation terminated.","position":{},"original":"compilation terminated."}
AGPBI: {"kind":"SIMPLE","text":"make.exe: *** [C:\\Users\\QuocN\\StudioProjects\\FBReaderJ-master\\fBReaderJmaster\\build\\intermediates\\ndk\\debug\\obj/local/arm64-v8a/objs/DeflatingDecompressor-v3/C_\\Users\\QuocN\\StudioProjects\\FBReaderJ-master\\fBReaderJmaster\\src\\main\\jni\\DeflatingDecompressor\\DeflatingDecompressor.o] Error 1","position":{},"original":"make.exe: *** [C:\\Users\\QuocN\\StudioProjects\\FBReaderJ-master\\fBReaderJmaster\\build\\intermediates\\ndk\\debug\\obj/local/arm64-v8a/objs/DeflatingDecompressor-v3/C_\\Users\\QuocN\\StudioProjects\\FBReaderJ-master\\fBReaderJmaster\\src\\main\\jni\\DeflatingDecompressor\\DeflatingDecompressor.o] Error 1"}

 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':fBReaderJmaster:compileDebugNdk'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Users\QuocN\AppData\Local\Android\ndk\ndk-build.cmd'' finished with non-zero exit value 2

**Comment by NemoNguyen** [comment]
Please help.

**Comment by liquiddandruff** [comment]
C:\Users\QuocN\StudioProjects\FBReaderJ-master\fBReaderJmaster\build\intermediates\ndk\debug\obj/local/arm64-v8a/objs/DeflatingDecompressor-**v3/C_\Users**\QuocN\StudioProjects\FBReaderJ-master\fBReaderJmaster\src\main\jni\DeflatingDecompressor\DeflatingDecompressor.o.d

That directory doesn't look right. Try figuring out what's wrong with your paths, fix it so it can properly find that file, then recompile.

**Comment by NemoNguyen** [comment]
Thanks for your help.
After i've found out the issue with the directory. Another issue comes out. 
Please help me, here is the log:

:fBReaderJmaster:compileDebugNdk
AGPBI: {"kind":"ERROR","text":"*** Android NDK: Aborting...    .  Stop.","sourcePath":"C:/Users/QuocN/AppData/Local/Android/ndk/build/core/add-application.mk","position":{"startLine":199},"original":""}

Thanks for your help.

**Comment by geometer** [comment]
Guys, are you sure this is a good place to discuss your coding issues?
