### ISSUE TITLE
[Feature Request] make it possible to use hardware left & right keys for page turning

### ISSUE THREAD

**Issue by intari** [geometer/FBReaderJ#345]
make it possible to use hardware left & right keys for page turning as option (in addition to using volume buttons) for devices which have hardware keyboards or can be used with hardware keyboards

**Comment by geometer** [comment]
If you are an end-user OR device manufacturer, that's possible. FBReader reads user-defined keymap.xml from
1) embedded FBReader resources
2) /system/usr/share/FBReader/keymap.xml
3) the books directory (first book directory, if you defined several)

(It reads all existing files from the list, in the order I listed them, latest definition for the key would be used.)

keymap.xml format should be clear from https://github.com/geometer/FBReaderJ/blob/f2f11431981d2938ec7e4b55876c07ca30a50c91/assets/default/keymap.xml

I have no idea how to add options for non-standard keys to FBReader preferences with no confusions for most users. In principle, that might be possible to write 'extra settings' plugin for FBReader that would be device-specific.
