### ISSUE TITLE
Display PDF without borders

### ISSUE THREAD

**Issue by jondo** [geometer/FBReaderJ#372]
The PDF plugin should have an option to generally display the pages of a PDF without white border.

(I guess that option might exist already. As a newbie user of FBReader I could not find it, however.)

**Comment by geometer** [comment]
Hi,

Sorry, I’m not sure what you mean “white border”. Could you please send me a screenshot?

Regards,

— Nikolay

**Comment by jondo** [comment]
It's just that many PDFs (e.g. scientific papers generated via LaTeX) have a border area without text all around each page. When reading such a document, it would be very useful if this border were clipped away, s.t. I don't have to manually zoom in.

**Comment by geometer** [comment]
Not sure, but may be “main (right) menu -> book options -> crop” is your solution.

**Comment by jondo** [comment]
Great, thank you! But I have to enter the crop size manually. It would be good to have an "autocrop" button. Should I change this issue's title for that or open another one?

**Comment by geometer** [comment]
Sure, edit this issue or close it and open a new one -- as you prefer. (Not sure it's clear for me how to implement autocrop -- but I will ask the PDF code author.)

**Comment by jondo** [comment]
Ok, I have entered issue #373 for that.
