### ISSUE TITLE
the bullet point in the file data/whatsnew/en.html represented as &bullet;

### ISSUE THREAD

**Issue by silencemanRain** [geometer/FBReaderJ#380]
the **bullet** point in the html file should be represented as **'& bull;'**, but I found that some Internet browsers can parse it correctly. So i recommend that add **'& bullet'**; in the file formats/html/htl.ent

**Comment by geometer** [comment]
Ha-ha. Thanks! Will add "bullet" entity and will also update whatsnew files.

**Comment by geometer** [comment]
Done
