### ISSUE TITLE
Don't open PDF and DJVU in Android 6.0.1

### ISSUE THREAD

**Issue by proninyaroslav** [geometer/FBReaderJ#384]
Hello. Djvu and PDF plugins installed, but error takes off "Can't open the book." Logs are included.
[log_djvu.txt](https://github.com/geometer/FBReaderJ/files/115303/log_djvu.txt)
[log_pdf.txt](https://github.com/geometer/FBReaderJ/files/115302/log_pdf.txt)

**Comment by geometer** [comment]
Install updates 1.5.5 for both plugins. Or just go to device->settings and switch on storage permission for both apps.
