### ISSUE TITLE
ePub3 is not supported yet

### ISSUE THREAD

**Issue by xiebopublic** [geometer/FBReaderJ#39]
My test ePub3 file is downloaded from http://code.google.com/p/epub-samples/downloads/detail?name=cc-shared-culture-20120130.epub

When open this epub3 file using FBReaderJ 2.0beta6, video and audio could not be played.

**Comment by DhairyashilBhosale** [comment]
II checked this EPUB3 file on Android5, and the video from this file are working but the audio is not supported. for playing video install vlc or other video player so Fbreader will play the files. but audio is not played by fbreader so for that need to add support for audio files in EPUB3 rendering library.

**Comment by xiebopublic** [comment]
close it
