### ISSUE TITLE
FbReaderJ is not working after successfully build on Ubutu14.04 in eclipse Mars and Studio

### ISSUE THREAD

**Issue by DhairyashilBhosale** [geometer/FBReaderJ#401]
Dear all,
                As per given following link, I tried to build FBreaderJ-2.5.10 on ubuntu14.04 using eclipse and android studio.

**I tried following steps using Eclipse-Mars:**

1) [http://howtobuildfbreaderj.blogspot.in/2012/01/how-to-build-fbreaderj-fbreader-on.html](http://howtobuildfbreaderj.blogspot.in/2012/01/how-to-build-fbreaderj-fbreader-on.html)
2) [http://www.goldyliang.net/blog/how-to-build-fbreaderj-android/](http://www.goldyliang.net/blog/how-to-build-fbreaderj-android/)

1) Download FBReaderJ through 'git clone'.
2) compile all Natives file like C using 'ANT' builder 
3) added Android-SDK and NDK path in local.properties and changes the target  to 'target=android-19' in project.properties in all 'third-party' directories.
4) While compiling the the FBreaderJ give properly build and generate FBreader.apk file. 
5) But after installing akp file on device it gives message like: 'Unfortunately Stopped'. its doesn't open launch the App. 

**On Android-Studio:**

Using this following link I tried to build FBReaderJ in Android Studio:

1)[ https://github.com/liquiddandruff/FBReaderJ/blob/android_studio/README.md]( https://github.com/liquiddandruff/FBReaderJ/blob/android_studio/README.md)

I got following observation: 

1) It properly build and install the FBReader on android device.
2) But while opening the EPUB file in reader it shows it in zip format, It can not render the EPUB file or any other files.

The provided FBreaderJ source is of OLD version, so is new version's is opens? 

**SO, PLEASE ANY HAVE PROPER BUILD STEPS FOR FBREADERJ ? on Linux platform.**

With Regards,
Dhairyashil

**Comment by geometer** [comment]
Out of topic. This tracker is for FBReader bugs, not for discussing your coding issues.
