### ISSUE TITLE
No more changes?

### ISSUE THREAD

**Issue by boussouira** [geometer/FBReaderJ#404]
Hi,
It's been a while since the last commit, is the project some how become closed?

Thank you

**Comment by nvllsvm** [comment]
The latest release on GitHub is 2.5.9, while the latest release on the Play Store is 2.6.13.

Seems that the developers are essentially giving up on open source contributions since switching to a Free/Premium model. Bah!

**Comment by boussouira** [comment]
latest release on the Play Store is 2.7.2 now

**Comment by nvllsvm** [comment]
@geometer  Can we can get an official statement of future source releases?

**Comment by redmanmale** [comment]
Such irony: the issue theme and issue number.

**Comment by boussouira** [comment]
Yeah, this could be related to #402 to view new changes
