### ISSUE TITLE
Error when Ant Release + How to build on Android Studio?

### ISSUE THREAD

**Issue by sinhpn92** [geometer/FBReaderJ#412]
The first, thanks so much this open source.

I have one error and 1 question when use FBReaderJ.

Error:
I get error "Native libraries are not up-to-date. Please run ndk-build manually." when run "ant release". I searched in the internet but I can't fix it. I use latest version ndk r12b and I see that in the definitions.mk file have line "$1:| $$(__ndk_file_dir)".
Have any suggestion for thí error?

Question:
How can build FBReaderJ on Android Studio?

Thanks for your times

**Comment by Mayur-007** [comment]
@sinhpn92 Were you able to build on Studio ?

**Comment by sinhpn92** [comment]
Thanks your review. It works fine.

**Comment by Mayur-007** [comment]
@sinhpn92 I want to implement in Studio,
can you help me ?

**Comment by sinhpn92** [comment]
@Mayur-007 what about your error? What's this? 
I find a project had converted to Android Studio project here: https://github.com/liquiddandruff/FBReaderJ

**Comment by RFlame** [comment]
@sinhpn92  I also have this error,can you tell me how to fix it? thank you.
