### ISSUE TITLE
Bundling Expat 2.0.1

### ISSUE THREAD

**Issue by hartwork** [geometer/FBReaderJ#415]
Hi there!

It seems you have Expat 2.0.1 bundled in directory `jni/expat-2.0.1`. Is that used in any way still?
If so: Are you aware that Expat 2.0.1 is rather old and contains security issues that have been fixed in later releases upstream?

Thanks and best, Sebastian

**Comment by geometer** [comment]
Very interesting, I did not know. Yes, we use it for parsing books. Do not think *security* issues are applicable in our case, but it should be updated of course.

**Comment by hartwork** [comment]
Why would security issues not apply?

**Comment by hartwork** [comment]
Any news?

**Comment by hartwork** [comment]
Closing to keep https://github.com/issues clean for myself…
