### ISSUE TITLE
Bundles vulnerable copy of Expat - please update to 2.2.4

### ISSUE THREAD

**Issue by hartwork** [geometer/FBReaderJ#456]
Hi!

This repository [bundles an outdated vulnerable copy of Expat 2.0.1](https://github.com/geometer/FBReaderJ/tree/master/jni/expat-2.0.1/lib). Please update your copy to version 2.2.2 with the latest security fixes. A change log with details is available at https://github.com/libexpat/libexpat/blob/master/expat/Changes . Thank you!

Best

&nbsp;
Sebastian

**Comment by hartwork** [comment]
Ping, anyone got a minute? :)

**Comment by hartwork** [comment]
Anyone got a minute?

**Comment by hartwork** [comment]
Any news?

**Comment by hartwork** [comment]
Closing to keep https://github.com/issues clean for myself…

**Comment by ildar** [comment]
better switch to something that is supported. E.g. LxReader for Android.
