### ISSUE TITLE
Tag latest versions

### ISSUE THREAD

**Issue by ildar** [geometer/FBReaderJ#464]
Please mark the latest versions with GIT tags, as the last tag I see is 2.6beta*
Thanks in advance.

**Comment by jeremy447** [comment]
Can you do it please ? Thanks !

**Comment by geometer** [comment]
Latest open source version (2.6.15 for Android 2.x and for Nook) is tagged in another repo: https://github.com/geometer/FBReader-Android-2

Code for Android 3 and higher is not open source at the moment. And this repo is dead.

**Comment by ildar** [comment]
Спасибо за пояснение!
