### ISSUE TITLE
Updated ta (Tamil) translation

### ISSUE THREAD

**Issue by magimaiprakash** [geometer/FBReaderJ#477]
I have translated your application into `ta` (*Tamil*). Here is the xml:
```xml

```

---

*Translation made with [Stringlate](https://github.com/LonamiWebs/Stringlate).*

**Comment by magimaiprakash** [comment]
Sorry people I am kind of new to Github and Translating stuff, I did the translating the in Stringlate app, but nothing is here

**Comment by magimaiprakash** [comment]
Due to some error in the Stringlate app, I cannot provide the translated xml here, so please give me some time to figure it out.

**Comment by geometer** [comment]
Hi,

Thank you. Please send it to geometer@fbreader.org.
